// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPW5nT2OWSS7lY4Y03VZdfsvihR6996IA',
    appId: '1:618095960112:web:a731e456bba2ef7bab4df5',
    messagingSenderId: '618095960112',
    projectId: 'junko-san-05zvr7',
    authDomain: 'junko-san-05zvr7.firebaseapp.com',
    storageBucket: 'junko-san-05zvr7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3QlqdGXNrEY7FVK05o56-BLX3GV8UCpE',
    appId: '1:618095960112:android:448fbcb49c68a26fab4df5',
    messagingSenderId: '618095960112',
    projectId: 'junko-san-05zvr7',
    storageBucket: 'junko-san-05zvr7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAxdIhrzZfbVRmqGVdf3DWibZ8F5L2xRM',
    appId: '1:618095960112:ios:4573fed61ef5ab84ab4df5',
    messagingSenderId: '618095960112',
    projectId: 'junko-san-05zvr7',
    storageBucket: 'junko-san-05zvr7.firebasestorage.app',
    iosBundleId: 'com.luxurytouch.massageAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAxdIhrzZfbVRmqGVdf3DWibZ8F5L2xRM',
    appId: '1:618095960112:ios:4573fed61ef5ab84ab4df5',
    messagingSenderId: '618095960112',
    projectId: 'junko-san-05zvr7',
    storageBucket: 'junko-san-05zvr7.firebasestorage.app',
    iosBundleId: 'com.luxurytouch.massageAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPW5nT2OWSS7lY4Y03VZdfsvihR6996IA',
    appId: '1:618095960112:web:f7c326ab6e60c49cab4df5',
    messagingSenderId: '618095960112',
    projectId: 'junko-san-05zvr7',
    authDomain: 'junko-san-05zvr7.firebaseapp.com',
    storageBucket: 'junko-san-05zvr7.firebasestorage.app',
  );
}
